[[libcgal_5_4_julia]]
arch = "x86_64"
git-tree-sha1 = "384c5c31254d8c8436f6ed1bc39fc2e3c857ff4e"
os = "macos"

    [[libcgal_5_4_julia.download]]
    sha256 = "2fc2130aafc8c6b1b04bc114cd14269e2a8da0e26befafef27898fbb1338a35b"
    url = "https://github.com/mathieu17g/libcgal_5_4_jll.jl/releases/download/libcgal_5_4_julia-v0.18.7+0/libcgal_5_4_julia.v0.18.7.x86_64-apple-darwin.tar.gz"
