[[libcgal_5_4_julia]]
arch = "x86_64"
git-tree-sha1 = "649d4524ab442377b99bceb58557577adc7b3bbb"
os = "macos"

    [[libcgal_5_4_julia.download]]
    sha256 = "c9cadfccc58ff590b06eda00c32ad5fbbdb7aa09b84bcbebf34b79a13f75dcff"
    url = "https://github.com/mathieu17g/libcgal_5_4_jll.jl/releases/download/libcgal_5_4_julia-v0.18.7+0/libcgal_5_4_julia.v0.18.7.x86_64-apple-darwin.tar.gz"
